name: Test
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: npm cit

  e2e:
    runs-on: ${{ matrix.os }}-latest
    strategy: { matrix: { os: [ubuntu, macOS] } }
    steps:
    - uses: actions/checkout@v2
    - uses: ./
      with:
        brew-version: 2.2.11
    - run: brew --env
    - run: brew help
